version: "3.8"

services:
  rails-app:
    build: .
    volumes:
      - .:/app
      - bashhistory:/commandhistory
      - rails-gems:/gems
    ports:
      - "3001:3001"

volumes:
  rails-gems:
  bashhistory:
